"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message
from .retry import retry_async
from . import paperless_meta
from .document_row import build_export_filename
from .file_linking import export_pdf

def cache_is_fresh(all_dir: str, max_age_seconds: int = 3600) -> bool:
    """Prüft, ob der Cache im .all-Verzeichnis jünger als max_age_seconds ist."""
    ts_file = os.path.join(all_dir, "cache.timestamp")
    try:
        if not os.path.exists(ts_file):
            return False
        mtime = os.path.getmtime(ts_file)
        age = time.time() - mtime
        if age < max_age_seconds:
            message(f"🕒 Cache im {all_dir} ist {int(age)}s alt – überspringe Neuaufbau.", "both")
            return True
        else:
            message(f"♻️ Cache im {all_dir} ist zu alt ({int(age)}s) – wird neu aufgebaut.", "both")
            return False
    except Exception as e:
        message(f"⚠️ Fehler bei Cacheprüfung: {e}", "both")
        return False


def update_cache_timestamp(all_dir: str):
    """Setzt oder aktualisiert den Timestamp des Cache."""
    ts_file = os.path.join(all_dir, "cache.timestamp")
    try:
        with open(ts_file, "w") as f:
            f.write(str(int(time.time())))
        message(f"🗓️ Cache-Timestamp aktualisiert ({ts_file})", "log")
    except Exception as e:
        message(f"⚠️ Fehler beim Setzen des Cache-Timestamps: {e}", "both")


from pypaperless.models.generators.page import Page


async def safe_document_iterator(paperless):
    page_iter = aiter(paperless.documents.pages())

    while True:
        try:
            page: Page = await retry_async(lambda: anext(page_iter), desc="Lade Dokument-Seite")
        except StopAsyncIteration:
            break
        except Exception as e:
            message(f"Fehler beim Laden einer Seite: {e}")
            break

        for doc in page.items:
            yield doc

SP_INDEX_FILENAME = ".sp_index.json"



async def build_all_cache(paperless, export_dir, log_path=None):
    """
    Baut den .all-Cache – seit dem SP-Umbau NUR NOCH für PDFs. JSON-Dateien
    werden nicht mehr hier abgelegt, sondern von build_sp_structure() direkt
    im SP-Baum (SP/<aufgelöster Ordner>/) gepflegt.
    """
    def log(msg):
        if log_path:
            message( msg)

    all_dir = os.path.join(export_dir, ".all")
    os.makedirs(all_dir, exist_ok=True)

    if cache_is_fresh(all_dir):
        #message("✅ Cache ist aktuell – überspringe Aufbau", "both")
        return

    # Schneller Count über .all()
    doc_ids = await retry_async(lambda: paperless.documents.all(), desc="Zähle Dokumente")
    total = len(doc_ids)

    done = 0
    cached = 0
    bar = tqdm(total=total, desc="PDFs cachen: 0✓ / 0↓", unit="doc")

    async for doc in safe_document_iterator(paperless):
        try:
            pdf_filename = build_export_filename(doc, kind="pdf", meta_cache=paperless_meta._paperless_meta_cache)
            pdf_path = os.path.join(all_dir, pdf_filename)

            updated = False
            if not os.path.exists(pdf_path):
                ok = await export_pdf(doc, working_dir=all_dir)
                updated = updated or ok

            if updated:
                done += 1
            else:
                cached += 1

            bar.update(1)
            bar.set_description(f"PDFs cachen: {cached}✓ / {done}↓")

            # minimaler Cooldown, um Verbindungsabbrüche zu reduzieren
            await asyncio.sleep(0.05)

        except Exception as e:
            # Fängt alles, damit ein einzelnes Dokument nicht den gesamten Lauf killt
            message(f"Fehler bei Doc {getattr(doc,'id','?')}: {e}", target="log", level="warn")
            bar.update(1)

    update_cache_timestamp(all_dir)


def extract_doc_id(filename):
    """Extrahiere die Dokument-ID aus einem Dateinamen wie '874--irgendwas.pdf'."""
    try:
        return int(filename.split('--', 1)[0])
    except (ValueError, IndexError):
        return None

async def cleanup_all_dir(paperless, all_dir, log_path=None):
    """
    Bereinigt das .all-Verzeichnis – seit dem SP-Umbau nur noch PDFs (JSON
    liegt jetzt im SP-Baum). Alte .json-Dateien aus der Zeit vor dem Umbau
    werden hier einmalig als Migrations-Altlast entfernt, unabhängig von
    ihrer Gültigkeit.
    """
    message( "Bereinige .all-Verzeichnis...")

    # Aktuelle Dokument-IDs abrufen
    valid_doc_ids = set(await retry_async(lambda: paperless.documents.all(), desc="Lade gültige Dokument-IDs"))

    removed_files = 0
    removed_legacy_json = 0
    for filename in os.listdir(all_dir):
        if filename.endswith(".json"):
            # Migrations-Altlast: JSON gehört seit dem SP-Umbau nicht mehr hierher.
            file_path = os.path.join(all_dir, filename)
            try:
                os.remove(file_path)
                removed_legacy_json += 1
            except Exception as e:
                message(message=f"Fehler beim Löschen alter JSON {filename}: {e}")
            continue

        if not filename.endswith(".pdf"):
            continue

        doc_id = extract_doc_id(filename)
        if doc_id is None or doc_id not in valid_doc_ids:
            file_path = os.path.join(all_dir, filename)
            try:
                os.remove(file_path)
                removed_files += 1
                message(f"Entfernt: {filename}")
            except Exception as e:
                message(message=f"Fehler beim Löschen von {filename}: {e}")

    if removed_legacy_json:
        message(f"Migration: {removed_legacy_json} alte JSON-Datei(en) aus .all/ entfernt (liegen jetzt im SP-Baum).")
    message(text=f"Bereinigung abgeschlossen: {removed_files} PDF-Datei(en) entfernt.")


