"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message

def get_log_filename(script_name, log_dir, suffix="progress"):
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    if suffix == "log":
        return os.path.join(log_dir, f"{script_name}__{timestamp}.log")
    else:
        return os.path.join(log_dir, f"{script_name}__{timestamp}.{suffix}.log")

# ---------------------- Configuration Loading ----------------------
def load_config(config_path):
    """Lädt eine INI-Konfigurationsdatei, gibt None zurück bei Fehlern."""
    #message("process...")
    config = configparser.ConfigParser()
    try:
        config.read(config_path)
        return config
    except configparser.DuplicateSectionError as e:
        print(f"❌ Fehlerhafte INI-Datei (Duplicate Section): {config_path} – wird übersprungen. {e}")
        return None

# ----------------------
def get_script_name():
    """Return the name of the current script without extension."""
    return os.path.splitext(os.path.basename(sys.argv[0]))[0]

# ----------------------
def load_config_from_script():
    """Load the configuration from the ini file with a priority for the .ufe.ini file."""
    script_name = get_script_name()
    ufe_ini_path = f"{script_name}.ufe.ini"
    ini_path = f"{script_name}.ini"

    # Try to load the .ufe.ini file first
    if os.path.exists(ufe_ini_path):
        message(f"Using config file: {ufe_ini_path}")
        return load_config(ufe_ini_path)
    # Fallback to the .ini file
    elif os.path.exists(ini_path):
        message(f"Using config file: {ini_path}")
        return load_config(ini_path)
    else:
        print(f"Configuration files '{ufe_ini_path}' and '{ini_path}' not found.")
        sys.exit(1)

# ----------------------

def should_export(export_dir: str, frequency: str, config_mtime: float) -> tuple[bool, str]:

    base_name = os.path.basename(export_dir)
    latest_xlsx_mtime = None

    for fname in os.listdir(export_dir):
        if fname.endswith(".xlsx") and (
            fname.startswith(f"{base_name}-") or fname == f"{base_name}.xlsx"
        ):
            fpath = os.path.join(export_dir, fname)
            mtime = os.path.getmtime(fpath)
            if latest_xlsx_mtime is None or mtime > latest_xlsx_mtime:
                latest_xlsx_mtime = mtime

    if latest_xlsx_mtime is None:
        return True, "Keine .xlsx-Datei vorhanden"

    if config_mtime > latest_xlsx_mtime:
        config_time = datetime.fromtimestamp(config_mtime).strftime('%Y-%m-%d %H:%M:%S')
        xlsx_time = datetime.fromtimestamp(latest_xlsx_mtime).strftime('%Y-%m-%d %H:%M:%S')
        return True, (
            f"Config modified: "
            f"(INI: {config_time}, XLSX: {xlsx_time})"
        )
    
    now = datetime.now()
    last_export = datetime.fromtimestamp(latest_xlsx_mtime)
    frequency = frequency.lower().strip()

    readable_time = last_export.strftime('%Y-%m-%d %H:%M:%S')
    # Bedingung beschreiben
    if frequency == "hourly":
        next_export = last_export + timedelta(hours=1)
        if now > next_export:
            return True, f"hourly: last={readable_time}, next={next_export}, now={now}"
        else:
            return False, f"noExport: hourly until {next_export.strftime('%Y-%m-%d %H:%M:%S')}"
    
    elif frequency == "4hourly":
        next_export = last_export + timedelta(hours=4)
        if now > next_export:
            return True, f"4hourly: last={readable_time}, next={next_export}, now={now}"
        else:
            return False, f"noExport: 4hourly until {next_export.strftime('%Y-%m-%d %H:%M:%S')}"

    elif frequency in ("daily", "weekday"):
        next_export = last_export + timedelta(days=1)
        if now > next_export:
            return True, f"daily: last={readable_time}, next={next_export}, now={now}"
        else:
            return False, f"noExport: daily until {next_export.strftime('%Y-%m-%d %H:%M:%S')}"
    
    elif frequency == "weekly":
        next_export = last_export + timedelta(days=7)
        if now > next_export:
            return True, f"weekly: last={readable_time}, next={next_export}, now={now}"
        else:
            return False, f"noExport: weekly until {next_export.strftime('%Y-%m-%d')}"
    
    elif frequency == "monthly":
        next_month = (last_export.replace(day=1) + timedelta(days=32)).replace(day=1)
        if now > next_month:
            return True, f"monthly: last={last_export.strftime('%Y-%m')}, next={next_month.strftime('%Y-%m')}, now={now.strftime('%Y-%m-%d')}"
        else:
            return False, f"noExport: monthly until {next_month.strftime('%Y-%m-%d')}"

    elif frequency == "yearly":
        next_year = datetime(last_export.year + 1, 1, 1)
        if now > next_year:
            return True, f"yearly: last={last_export.year}, next={next_year.year}, now={now.year}"
        else:
            return False, f"noExport: yearly until {next_year.year}"
    return False, (
        f"noExport: last file {readable_time}, "
    )

