"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message
from . import paperless_meta
from .paperless_meta import getmeta
from .formatting import parse_currency, format_currency

def sanitize_filename(filename):
    """
    Remove or replace characters in the filename that are problematic in common filesystems.
    """
    original = filename

    # Ersetze bekannte problematische Zeichen (Windows, Samba, NAS, etc.)
    sanitized = re.sub(r'[<>:"/\\|?*\[\]]', '-', filename)  # auch [ und ] ersetzen

    # Optional: Leerzeichen am Anfang/Ende oder doppelte Minus entfernen
    sanitized = re.sub(r'\s+', ' ', sanitized).strip()
    sanitized = re.sub(r'-{2,}', '-', sanitized)

    # Truncate auf maximale Pfadlänge
    sanitized = sanitized[:255]

  #  if sanitized != original:
  #      message(f"Dateiname bereinigt: '{original}' → '{sanitized}'", target="both")

    return sanitized

def build_export_filename(doc, kind, meta_cache=None):
    """
    Build a consistent export filename including document type, correspondent, and title.
    Pattern: <id>--<document_type>--<correspondent>--<title>.<kind>
    """
    meta = meta_cache or paperless_meta._paperless_meta_cache

    doc_type_name = "Unbekannt"
    correspondent_name = "Unbekannt"

    if meta:
        try:
            doc_type_name = getmeta("document_type", doc, meta) or "Unbekannt"
        except Exception:
            pass
        try:
            correspondent_name = getmeta("correspondent", doc, meta) or "Unbekannt"
        except Exception:
            pass

    sanitized_type = sanitize_filename(doc_type_name)
    sanitized_correspondent = sanitize_filename(correspondent_name)
    sanitized_title = sanitize_filename(doc.title)

    return f"{doc.id}--{sanitized_type}--{sanitized_correspondent}--{sanitized_title}.{kind}"

# Remove characters not allowed by Excel (control chars 0x00-0x1F except tab/newline/carriage return)
_XL_ILLEGAL_RE = re.compile(r"[\x00-\x08\x0B\x0C\x0E-\x1F]")

def clean_for_excel(value):
    """Return value with illegal worksheet characters removed (strings only)."""
    if value is None:
        return None
    if isinstance(value, str):
        return _XL_ILLEGAL_RE.sub('', value)
    return value

# ----------------------


def process_custom_fields(meta, doc):
    """
    - meta['custom_fields']: Dict[id -> Objekt], Objekt._data enthält u.a. 'data_type' und evtl. 'extra_data'
    - doc['custom_fields']: Liste von Einträgen mit 'field' (ID) und 'value'

    Rückgabe:
      custom_fields: dict mit aufgelösten Werten/Labels
      currency_fields: Liste von Feldnamen (für Summen)
    """
    custom_fields = {}
    currency_fields = []

    meta_cf = meta.get("custom_fields") or {}
    doc_cf_list = doc.get("custom_fields") or []

    for entry in doc_cf_list:
        field_id = entry.get("field")
        if not field_id or field_id not in meta_cf:
            continue

        meta_obj = meta_cf[field_id]
        field_name = getattr(meta_obj, "name", f"field_{field_id}")

        data = getattr(meta_obj, "_data", {}) or {}
        field_type = (data.get("data_type") or "").lower()
        field_value = entry.get("value")

        # Choices/Options einsammeln (Liste oder Dict → Mapping)
        extra = (data.get("extra_data") or {})
        choices = extra.get("select_options") or extra.get("choices") or extra.get("options") or []

        choice_map = {}
        if isinstance(choices, dict):
            choice_map = {str(k): v for k, v in choices.items()}
        elif isinstance(choices, list):
            for ch in choices:
                if isinstance(ch, dict):
                    key = ch.get("value") or ch.get("id") or ch.get("key") or ch.get("slug") or ch.get("label")
                    label = ch.get("label") or ch.get("name") or ch.get("value") or ch.get("slug") or str(ch)
                else:
                    key = str(ch)
                    label = str(ch)
                if key is not None:
                    choice_map[str(key)] = label

        def resolve_choice(v):
            if v is None:
                return "none"
            if isinstance(v, list):  # multiselect
                return ", ".join(str(choice_map.get(str(x), x)) for x in v)
            return choice_map.get(str(v), v)

        if field_type in ("monetary", "currency"):
            numeric_value = parse_currency(field_value)  # deine bestehende Funktion
            custom_fields[field_name] = numeric_value
            custom_fields[f"{field_name}_formatted"] = format_currency(field_value)  # deine bestehende Funktion
            currency_fields.append(field_name)

        elif field_type in ("select", "multiselect", "choice", "choices"):
            custom_fields[field_name] = resolve_choice(field_value)

        else:
            custom_fields[field_name] = field_value

    return custom_fields, currency_fields

