"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message, safe_unlink, cleanup_old_files
from .versioning import get_script_version
from .document_row import sanitize_filename, clean_for_excel

def debug_write(df, directory):
    # Debug-Stubs deaktiviert
    pass

def _excel_safe_value(value):
    """openpyxl kann nur Skalare (str/int/float/bool/date) schreiben.
    Listen/Dicts/Sets (z.B. bei Tags, Custom Fields, storage_path)
    werden hier zu einem lesbaren String zusammengefasst.
    Zusätzlich: für Excel/XML illegale Steuerzeichen entfernen
    (verhindert IllegalCharacterError bei OCR-/Custom-Field-Werten)."""
    if value is None:
        return None
    if isinstance(value, (str, int, float, bool)):
        return clean_for_excel(value)
    if isinstance(value, (list, tuple, set)):
        return clean_for_excel(", ".join(str(_excel_safe_value(v)) for v in value))
    if isinstance(value, dict):
        return clean_for_excel(", ".join(f"{k}={v}" for k, v in value.items()))
    return clean_for_excel(str(value))


def _write_data_sheet(wb, sheet_title, data, url):
    """
    Schreibt EIN Daten-Sheet (Header + Zeilen + Hyperlinks + Tabellen-Styling)
    in die übergebene Workbook. Rückgabe: (headers, normalized_data).

    Ausgelagert aus export_to_excel(), damit sowohl der normale Query-Export
    (ein Sheet "Tabelle") als auch der SP-Baum (zwei Sheets "current"+"sub")
    dieselbe Logik nutzen – keine Doppelpflege.
    """
    from openpyxl.utils import get_column_letter

    all_headers = []
    header_set = set()
    for row in data:
        for k in row.keys():
            if k not in header_set:
                header_set.add(k)
                all_headers.append(k)

    normalized_data = []
    for row in data:
        fixed = {h: row.get(h, None) for h in all_headers}
        normalized_data.append(fixed)
    data = normalized_data

    if not data:
        return all_headers, data

    paperless_url = str(url).rstrip("/")
    ws = wb.create_sheet(sheet_title)

    for col_idx, col_name in enumerate(all_headers, start=1):
        ws.cell(row=1, column=col_idx, value=clean_for_excel(col_name))

    plain_row = 2
    for row in data:
        for col_idx, col_name in enumerate(all_headers, start=1):
            ws.cell(row=plain_row, column=col_idx, value=_excel_safe_value(row[col_name]))
        plain_row += 1

    last_plain_row = plain_row - 1
    last_plain_col = get_column_letter(len(all_headers))
    plain_ref = f"A1:{last_plain_col}{last_plain_row}"

    link_col_index = None
    for idx, h in enumerate(all_headers, start=1):
        if h == "LINK":
            link_col_index = idx
            break

    if link_col_index:
        for r_ in range(2, last_plain_row + 1):
            doc_id = ws.cell(row=r_, column=1).value
            link_cell = ws.cell(row=r_, column=link_col_index)
            link_cell.value = doc_id
            link_cell.hyperlink = f"{paperless_url}/documents/{doc_id}"
            link_cell.style = "Hyperlink"

    raw_tbl = sheet_title
    safe_tbl = re.sub(r'[^A-Za-z0-9]', '', raw_tbl)
    if not safe_tbl:
        safe_tbl = "Data"
    table_name = f"tbl{safe_tbl}"
    data_table = Table(displayName=table_name, ref=plain_ref)
    style = TableStyleInfo(name="TableStyleMedium9", showRowStripes=True, showColumnStripes=False)
    data_table.tableStyleInfo = style
    ws.add_table(data_table)

    return all_headers, data


def _write_meta_sheet(wb, script_name, directory, fullfilename, currency_columns, headers, meta,
                       query, custom_field_query, frequency, doc_count, url, extra_stats=None):
    """
    Schreibt das Metadaten-Sheet ("📊 Metadaten"). Ausgelagert aus
    export_to_excel(), s. _write_data_sheet() für den Hintergrund.

    extra_stats: optionale Liste von (Label, Wert)-Tupeln, die zusätzlich
    unter "📊 Dokument-Statistik" eingefügt werden (z.B. current/sub-Zahlen
    für die SP-Baum-Mappen).
    """
    ws_meta = wb.create_sheet("📊 Metadaten")
    paperless_url = str(url).rstrip("/")

    rows = []
    r = rows.append

    r(["HeaderInfo", f"{script_name} -- {directory} -- {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} -- {pwd.getpwuid(os.getuid()).pw_name} -- {os.uname().nodename}"])
    r(["", ""])
    r(["📝 Exportinformationen", ""])
    r(["Script-Version", get_script_version()])
    r(["Export-Datum", datetime.now().strftime("%Y-%m-%d %H:%M:%S")])
    r(["Hostname", os.uname().nodename])
    r(["Username", pwd.getpwuid(os.getuid()).pw_name])
    r(["", ""])

    xlsx_size = os.path.getsize(fullfilename) if os.path.exists(fullfilename) else 0
    r(["📁 Verzeichnisse & Dateigrößen", ""])
    r(["Export-Verzeichnis", directory])
    r(["Excel-Datei", os.path.basename(fullfilename)])
    r(["Größe (xlsx)", f"{xlsx_size/1024:.2f} KB"])
    r(["JSON-Dateien", len([f for f in os.listdir(directory) if f.endswith('.json')])])
    r(["PDF-Dateien", len([f for f in os.listdir(directory) if f.endswith('.pdf')])])
    r(["", ""])

    r(["⚙️ Konfiguration (config.ini)", ""])
    r(["Query", query])
    safe_query = quote(str(query), safe="")
    safe_cf_query = quote(str(custom_field_query), safe="") if custom_field_query else None
    r(["API-Query-Link", f"{paperless_url}/api/documents/?query={safe_query}"])
    if custom_field_query:
        r(["API-Query-Link-CF", f"{paperless_url}/api/documents/?query={safe_query}&custom_field_query={safe_cf_query}"])
    r(["API-Query-Link-Raw", f"{paperless_url}/api/documents/?query={query}"])
    r(["Frequency", frequency])
    r(["", ""])

    r(["📊 Dokument-Statistik", ""])
    r(["Dokumente gesamt", doc_count])
    if extra_stats:
        for label, value in extra_stats:
            r([label, value])
    r(["Currency-Felder", ", ".join(currency_columns)])
    r(["Header-Spalten", ", ".join(headers)])
    r(["", ""])

    r(["🧩 Custom Fields", ""])
    all_custom_fields = [c for c in headers if c not in ("ID","LINK","Korrespondent","Titel","Tags","Seiten","Dokumenttyp","Speicherpfad")]
    r(["Anzahl Custom Fields", len(all_custom_fields)])
    r(["Custom Fields", ", ".join(all_custom_fields)])
    r(["", ""])

    def meta_names(meta_section):
        try:
            return [getattr(v, "name", str(k)) for k, v in (meta.get(meta_section) or {}).items()]
        except Exception:
            return []

    def add_horizontal_list(title, items):
        items_sorted = sorted(set(filter(None, items)))
        r([f"{title} (Anzahl)", len(items_sorted)])
        r([title, ""] + items_sorted)
        r(["", ""])

    add_horizontal_list("Storage Paths", meta_names("storage_paths"))
    add_horizontal_list("Korrespondenten", meta_names("correspondents"))
    add_horizontal_list("Dokumenttypen", meta_names("document_types"))
    add_horizontal_list("Tags", meta_names("tags"))
    add_horizontal_list("Custom Fields (Meta)", meta_names("custom_fields"))

    import importlib.metadata
    installed_packages = []
    for dist in importlib.metadata.distributions():
        name = dist.metadata.get("Name") or getattr(dist, "name", "unknown")
        version = dist.version or "unknown"
        installed_packages.append(f"{name}=={version}")
    installed_packages = sorted(installed_packages)
    r(["🐍 Python Umgebung", ""])
    r(["Python-Version", platform.python_version()])
    r(["Pakete (Top 10)", ", ".join(installed_packages[:10])])
    r(["", ""])

    for row_idx, row in enumerate(rows, start=1):
        for col_idx, value in enumerate(row, start=1):
            ws_meta.cell(row=row_idx, column=col_idx, value=clean_for_excel(value))

    hyperlink_fields = {"Query-Link": "Query-Link-Text",
                        "API-Query-Link": "API-Query-Link-Text",
                        "API-Query-Link-Raw": "API-Query-Link-Raw-Text"}

    for row_idx in range(len(rows), 0, -1):
        row = rows[row_idx - 1]
        if len(row) < 2:
            continue
        colA, colB = row[0], row[1]
        if colA in hyperlink_fields:
            cell = ws_meta.cell(row=row_idx, column=2)
            cell.hyperlink = colB
            cell.style = "Hyperlink"
            insert_label = hyperlink_fields[colA]
            ws_meta.insert_rows(row_idx + 1)
            ws_meta.cell(row=row_idx + 1, column=1, value=insert_label)
            ws_meta.cell(row=row_idx + 1, column=2, value=colB)

    from openpyxl.styles import Alignment, Border, Side
    thin = Side(style="thin", color="888888")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    for row_idx, row in enumerate(rows, start=1):
        for col_idx in range(1, len(row) + 1):
            cell = ws_meta.cell(row=row_idx, column=col_idx)
            cell.alignment = Alignment(vertical="top")
            cell.border = border

    for row_idx, row in enumerate(rows, start=1):
        if len(row) >= 2 and row[1] == "":
            ws_meta.cell(row=row_idx, column=1).font = Font(bold=True, size=13, color="1F4E79")


def _next_history_filename(directory, base_dirname):
    today = datetime.now().strftime("%Y%m%d")
    history_prefix = f"{base_dirname}-{today}"
    existing = []
    for f in os.listdir(directory):
        if f.startswith(history_prefix) and f.endswith(".xlsx"):
            try:
                n = int(f.rsplit("-", 1)[1].split(".")[0])
                existing.append(n)
            except Exception:
                pass
    next_num = 0 if not existing else max(existing) + 1
    return os.path.join(directory, f"{history_prefix}-{next_num}.xlsx")


def export_to_excel(data, file_path, script_name, currency_columns, dir, url, meta, maxfiles, query, custom_field_query, frequency):
    directory = os.path.dirname(file_path)
    base_dirname = os.path.basename(directory)
    fullfilename = _next_history_filename(directory, base_dirname)
    static_filename = os.path.join(directory, f"{base_dirname}.xlsx")

    wb = Workbook()
    ws_default = wb.active
    data_present = bool(data)
    if not data_present:
        ws_default.title = "Keine_Daten"
        ws_default.cell(row=1, column=1, value="Keine Dokumente gefunden.")
    else:
        wb.remove(ws_default)

    headers, norm_data = _write_data_sheet(wb, "Tabelle", data, url)
    _write_meta_sheet(wb, script_name, directory, fullfilename, currency_columns, headers, meta,
                       query, custom_field_query, frequency, doc_count=len(norm_data), url=url)

    wb.save(fullfilename)
    try:
        if os.path.exists(static_filename) or os.path.islink(static_filename):
            safe_unlink(static_filename)
        shutil.copy2(fullfilename, static_filename)
    except Exception as e:
        message(f"⚠️ Fehler beim Erstellen der statischen Datei: {e}", "both")


def export_sp_folder_excel(current_rows, sub_rows, current_currency, sub_currency,
                            file_path, script_name, dir, url, meta, folder_label):
    """
    Erzeugt EINE Excel-Mappe für einen SP-Baum-Ordner mit ZWEI Daten-Sheets:
      - "current": nur Dokumente, die DIREKT in diesem Ordner liegen
      - "sub":     Dokumente aus diesem Ordner UND allen Unterordnern

    Wird nur für Ordner erzeugt, die auch echte Dokumente direkt enthalten
    (siehe build_sp_excels() – reine Durchgangsordner bekommen keine Mappe).
    """
    directory = os.path.dirname(file_path)
    base_dirname = os.path.basename(directory)
    fullfilename = _next_history_filename(directory, base_dirname)
    static_filename = os.path.join(directory, f"{base_dirname}.xlsx")

    wb = Workbook()
    wb.remove(wb.active)

    current_headers, current_norm = _write_data_sheet(wb, "current", current_rows, url)
    sub_headers, sub_norm = _write_data_sheet(wb, "sub", sub_rows, url)

    combined_headers = list(current_headers)
    for h in sub_headers:
        if h not in combined_headers:
            combined_headers.append(h)
    combined_currency = list(dict.fromkeys(list(current_currency) + list(sub_currency)))

    _write_meta_sheet(
        wb, script_name, directory, fullfilename, combined_currency, combined_headers, meta,
        query=f"SP-Ordner: {folder_label}", custom_field_query=None, frequency="sp-shadow",
        doc_count=len(sub_norm), url=url,
        extra_stats=[("Dokumente direkt im Ordner (current)", len(current_norm)),
                     ("Dokumente inkl. Unterordner (sub)", len(sub_norm))],
    )

    wb.save(fullfilename)
    try:
        if os.path.exists(static_filename) or os.path.islink(static_filename):
            safe_unlink(static_filename)
        shutil.copy2(fullfilename, static_filename)
    except Exception as e:
        message(f"⚠️ Fehler beim Erstellen der statischen SP-Datei: {e}", "both")

# ----------------------
def has_file_from_today(directory):
    """
    Prüft, ob im angegebenen Verzeichnis eine Datei existiert,
    die heute erstellt oder zuletzt geändert wurde.
    """
    today = datetime.now().date()
    if not os.path.exists(directory):
        return False

    for filename in os.listdir(directory):
        file_path = os.path.join(directory, filename)
        if os.path.isfile(file_path):
            # Änderungszeitpunkt der Datei
            file_mtime = datetime.fromtimestamp(os.path.getmtime(file_path))
            if file_mtime.date() == today:
                return True
    return False
