"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message, cleanup_old_files
from .retry import retry_async
from .configutil import get_script_name
from .paperless_meta import fetch_paperless_meta
from .search import search_documents
from .excel_export import export_to_excel
from .document_row import sanitize_filename
from .file_linking import link_export_file, export_pdf
from .row_builder import build_document_row
from .sp_tree import find_sp_json_path, ensure_sp_json

async def exportThem(paperless, dir, query, custom_field_query, max_files, frequency, api_url, base_export_dir, sp_root=None, sp_index=None):
    count = 0 
    """Process and export documents"""
    document_data = []
    currency_columns = []  # Liste zur Speicherung aller Currency-Felder
    custom_fields = {}
    meta = await fetch_paperless_meta(paperless)

#    documents = [item async for item in paperless.documents.search(query)]

    documents = await retry_async(
       lambda: search_documents(paperless, query=query, custom_field_query=custom_field_query),
       desc=f"Dokumente für Query '{query}' CF '{custom_field_query}'"
       )

    # --- REMOVE OLD FILES: optional cleanup (keine Debug-Ausgabe) ---
    try:
        removed = 0
        for fname in os.listdir(dir):
            if fname.endswith(".pdf") or fname.endswith(".json"):
                fpath = os.path.join(dir, fname)
                try:
                    os.remove(fpath)
                    removed += 1
                except Exception as e:
                    message(f"⚠️ Fehler beim Löschen {fpath}: {e}", target="log")
        message(f"🧹 Entfernt: {removed} Datei(en) aus {dir}", target="log")
    except Exception as e:
        message(f"❌ Fehler beim Aufräumen in {dir}: {e}", target="log")

    #documents = await retry_async(
    #   lambda: collect_async_iter(paperless.documents.search(query)),
    #    desc=f"Dokumente für Query '{query}'"
    #)

    api_base = api_url.rstrip("/")

    for doc in tqdm(documents, desc=None, unit="doc", disable=True):
        count += 1

        row, doc_currency_columns, media_filename = await build_document_row(
            paperless=paperless, doc=doc, meta=meta, api_url=api_url
        )
        currency_columns.extend(doc_currency_columns)  # Speichere Currency-Felder
        document_data.append(row)

        # Exportiere das PDF des Dokuments
        #await export_pdf(doc, working_dir=dir)
        #export_json(paperless=paperless,doc=doc,working_dir=dir)
        # Statt export_pdf / export_json:
        # Nutze das zentrale .all im Export-Root (unabhängig vom Unterordner).
        all_dir = os.path.join(base_export_dir, ".all")

        try:
            method_pdf = link_export_file(doc, kind="pdf", working_dir=dir, all_dir=all_dir)
        except FileNotFoundError as e:
            # Falls der Cache die Datei nicht enthält, on-demand nachladen und erneut verlinken.
            try:
                ok = await export_pdf(doc, working_dir=all_dir)
                if ok:
                    method_pdf = link_export_file(doc, kind="pdf", working_dir=dir, all_dir=all_dir)
                else:
                    raise RuntimeError("PDF-Export schlug fehl")
            except Exception as e2:
                method_pdf = "ERROR"
                message(f"❌ PDF fehlt für Doc {doc.id}: {e2}", target="both", level="warn")
        except Exception as e:
            method_pdf = "ERROR"
            message(f"❌ PDF fehlt für Doc {doc.id}: {e}", target="both", level="warn")

        try:
            json_src = find_sp_json_path(doc.id, sp_root, sp_index) if sp_root else None
            if json_src is None:
                raise FileNotFoundError(f"Kein SP-Index-Eintrag für Doc {doc.id}")
            method_json = link_export_file(doc, kind="json", working_dir=dir, src_path=json_src)
        except FileNotFoundError as e:
            # Fallback: JSON on-demand direkt im SP-Baum erzeugen (z.B. Doc
            # fehlt (noch) im Index) und von dort verlinken.
            try:
                fallback_path = None
                if sp_root:
                    fallback_path = await ensure_sp_json(paperless=paperless, doc=doc, sp_root=sp_root, api_url=api_url)
                if not fallback_path:
                    raise RuntimeError("SP-JSON-Fallback lieferte keinen Pfad")
                method_json = link_export_file(doc, kind="json", working_dir=dir, src_path=fallback_path)
            except Exception as e2:
                method_json = "ERROR"
                message(f"❌ JSON fehlt für Doc {doc.id}: {e2}", target="both", level="warn")
        except Exception as e:
            method_json = "ERROR"
            message(f"❌ JSON fehlt für Doc {doc.id}: {e}", target="both", level="warn")

       # message(f"{doc.id}: PDF → {method_pdf} json → {method_json}", target="both")


    # Exportiere die gesammelten Daten nach Excel
    #path=doc._api_path 
    url=paperless._base_url

    last_dir = os.path.basename(dir)
    # Use the query for the Excel filename, but sanitize it to remove illegal characters (e.g., '*', '?', etc.).
    #safe_query = sanitize_filename(str(query) if query is not None else "")
    #if not safe_query:
        # Fallback to directory name if query is empty after sanitization
    safe_query = sanitize_filename(last_dir)

    excel_file = os.path.join(dir, f"{safe_query}-{datetime.now().strftime('%Y%m%d')}.xlsx")
    #export_to_excel(document_data, excel_file, get_script_name, currency_columns=currency_columns,dir=dir, url=url,meta=meta, maxfiles=max_files,query=query, frequency=frequency)
    export_to_excel(document_data, excel_file, get_script_name(), currency_columns=currency_columns, dir=dir, url=url, meta=meta, maxfiles=max_files, query=query, custom_field_query=custom_field_query, frequency=frequency)
    pdf_count = len([f for f in os.listdir(dir) if f.lower().endswith(".pdf")])
    excel_name = os.path.basename(excel_file)
    parent_name = os.path.basename(dir.rstrip(os.sep))
    print(f"+ {parent_name}: Excel erstellt – PDFs={pdf_count} | Datei={excel_name}")
    print()  # gewünschte Leerzeile nach Export-Ausgabe
    base_dirname = os.path.basename(dir)
    cleanup_old_files(
        dir,
        filename_prefix=f"{base_dirname}-",
        max_count_str=max_files,
        pattern="xlsx"
    )

#    log_message(progress_log_path, f"dir: {dir}, Documents exported: {len(document_data)}")
#    print(f"Exported Excel file: {excel_file}")

import time

