"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message, safe_unlink, _normalize_path
from .retry import retry_async
from . import paperless_meta
from .document_row import sanitize_filename, build_export_filename

async def export_pdf(doc, working_dir):
    """Exportiert ein Dokument als PDF mit Retry; bei endgültigem Fehler wird geloggt und übersprungen."""
    filename = build_export_filename(doc, kind="pdf", meta_cache=paperless_meta._paperless_meta_cache)
    pdf_path = os.path.join(working_dir, filename)

    try:
        download = await retry_async(lambda: doc.get_download(),
                                     desc=f"PDF-Download für Dokument {doc.id}")
        document_content = download.content
        if not document_content:
            message(f"Keine PDF-Daten für Dokument {doc.id} gefunden.", target="log", level="warn")
            return False

        with open(pdf_path, 'wb') as f:
            f.write(document_content)
        return True
    except Exception as e:
        message(f"PDF-Download fehlgeschlagen für Doc {doc.id}: {e}", target="log", level="warn")
        return False

# ----------------------


def get_document_json(paperless, doc, api_base=None):
    """Retrieve detailed document metadata (document JSON)."""
    api_token = paperless._token
    headers = {"Authorization": f"Token {api_token}"}
    if api_base:
        url = f"{api_base}/api/documents/{doc.id}/"
    else:
        path = doc._api_path
        url = f"{paperless._base_url}/{path}"

    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        return response.json()
    raise Exception(f"Failed to fetch document JSON: {response.status_code}")

def get_document_metadata(paperless, doc, api_base=None):
    """
    Fetch the /metadata/ endpoint directly to avoid pypaperless validation quirks.
    """
    api_token = paperless._token
    headers = {"Authorization": f"Token {api_token}"}
    if api_base:
        url = f"{api_base}/api/documents/{doc.id}/metadata/"
    else:
        url = f"{paperless._base_url}/{doc._api_path}/metadata/"

    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        return response.json()
    raise Exception(f"Failed to fetch document metadata: {response.status_code}")

# ---------------------- Excel Export Helpers ----------------------
# ----------------------

def find_cached_file(doc_id, all_dir, kind):
    """Findet Datei im .all-Verzeichnis anhand von doc_id und Dateityp ('pdf' oder 'json')"""
    prefix = f"{doc_id}--"
    suffix = f".{kind}"
    for fname in os.listdir(all_dir):
        if fname.startswith(prefix) and fname.endswith(suffix):
            return os.path.join(all_dir, fname)
    return None

import os
import shutil
import platform

def is_synology():
    uname = platform.uname()
    return (
        "synology" in uname.node.lower()
        or os.path.exists("/etc/synoinfo.conf")
        or os.path.exists("/etc.defaults/synoinfo.conf")
    )

def force_copy_mode():
    """
    Gibt True zurück, wenn per Umgebungsvariable 'FORCE_COPY=1' erzwungen wird,
    dass keine Symlinks oder Hardlinks verwendet werden sollen.
    """
    return os.environ.get("FORCE_COPY", "0") == "1"

import os
import shutil
import glob

def link_export_file(doc, kind, working_dir, all_dir=".all", src_path=None):
    """
    Links a cached file (pdf/json) from a source directory to the working
    directory. The filename will be in the format:
    [ID]--[DocumentType]--[Correspondent]--[Title].[kind]

    src_path: falls gesetzt, wird DIESE Datei als Quelle verwendet statt
    im .all-Verzeichnis zu suchen (z.B. eine JSON-Datei aus dem SP-Baum).
    """
    assert kind in ("pdf", "json")

    filename = build_export_filename(doc, kind=kind, meta_cache=paperless_meta._paperless_meta_cache)
    dest_path = os.path.join(working_dir, filename)
    dest_dir = os.path.dirname(dest_path)

    # Normalize for macOS Unicode edge cases
    dest_path = _normalize_path(dest_path)
    dest_dir = _normalize_path(dest_dir)

    if src_path is None:
        # Quelle im .all-Ordner finden (klassischer Weg, weiterhin für PDFs genutzt)
        src_path = find_cached_file(doc.id, all_dir=all_dir, kind=kind)
        if src_path is None:
            raise FileNotFoundError(f"Keine {kind.upper()}-Datei für Dokument {doc.id} im .all-Verzeichnis gefunden")
    elif not os.path.exists(src_path):
        raise FileNotFoundError(f"Angegebene {kind.upper()}-Quelldatei existiert nicht: {src_path}")
    src_path = _normalize_path(src_path)

    os.makedirs(dest_dir, exist_ok=True)

    # Alte Dateien mit gleicher doc.id löschen, wenn Name abweicht
    prefix = f"{doc.id}--"
    pattern = os.path.join(dest_dir, f"{prefix}*.{kind}")
    existing_files = glob.glob(pattern)

    for old_path in existing_files:
        if os.path.abspath(old_path) != os.path.abspath(dest_path):
            try:
                safe_unlink(old_path)
            except Exception as e:
                message(f"⚠️ Fehler beim Entfernen alter Datei: {old_path} → {e}", "both")

    # Prüfen ob Ziel existiert oder kaputter Symlink vorhanden ist
    if os.path.lexists(dest_path):
        try:
            if os.path.islink(dest_path) and os.path.realpath(dest_path) == os.path.realpath(src_path):
                return "symlink (OK)"
            elif os.path.exists(dest_path) and os.path.samefile(dest_path, src_path):
                return "hardlink/copy (OK)"
            else:
                safe_unlink(dest_path)
        except Exception as e:
            message(f"Fehler beim Entfernen von bestehender Datei: {e}", "both")
            safe_unlink(dest_path)

    # 🔁 Nur kopieren, wenn Umgebungsvariable gesetzt ist
    if force_copy_mode():
        try:
            shutil.copy2(src_path, dest_path)
            if os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
                return "copy (FORCE)"
        except Exception as e:
            raise RuntimeError(f"Konnte Datei nicht kopieren: {src_path}")

    # 🔗 Symlink versuchen (relativer Pfad!)
    try:
        rel_src_path = os.path.relpath(src_path, start=dest_dir)
        os.symlink(rel_src_path, dest_path)
        if os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
            return "symlink (neu)"
    except Exception as e:
        message(f"Symlink fehlgeschlagen: {type(e).__name__}: {e}", "both")
        message(f"                      : {rel_src_path}", "both")
        message(f"                      : {dest_path}", "both")

    # 🔗 Hardlink versuchen
    try:
        os.link(src_path, dest_path)
        if os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
            return "hardlink (neu)"
    except Exception as e:
        message(f"Hardlink fehlgeschlagen: {e}", "both")

    # Letzter Fallback: Kopieren
    try:
        shutil.copy2(src_path, dest_path)
        if os.path.exists(dest_path) and os.path.getsize(dest_path) > 0:
            return "copy (fallback)"
    except Exception as e:
        message(f"Kopie fehlgeschlagen: {e}", "both")

    raise RuntimeError(f"Zieldatei konnte nicht erstellt werden: {dest_path}")

