"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

def parse_currency(value):
    """Parst einen Währungswert wie 'EUR5.00' in einen Float."""
    try:
        # Entferne Währungszeichen (alles außer Ziffern, Punkt oder Minus)
        numeric_part = ''.join(c for c in value if c.isdigit() or c == '.' or c == '-')
        return float(numeric_part)
    except Exception as e:
        # print(f"Fehler beim Parsen des Währungswerts '{value}': {e}")
        return 0.0  # Fallback auf 0 bei Fehlern

# ----------------------
def format_currency(value, currency_locale="de_DE.UTF-8"):
    if value is None:
        return ""
    try:
        clean_value = ''.join(filter(str.isdigit, value))
        if not clean_value:
            return "0,00"
        value_float = float(clean_value) / 100
    except ValueError:
        value_float = 0.0

    try:
        formatted_value = locale.currency(value_float, grouping=True)
    except Exception as e:
        formatted_value = f"{value_float:.2f}"
    return formatted_value
from datetime import datetime, date

def format_date(val, output_format):
    """
    Nimmt datetime.date, datetime.datetime oder String entgegen und gibt
    'yyyy-mm' oder 'yyyy-mm-dd' zurück. Gibt None bei Fehlern.
    """
    if val is None:
        print(f"Date string is empty or None: {val}")
        return None

    # Bereits datetime/date?
    if isinstance(val, datetime):
        dt = val
    elif isinstance(val, date):
        dt = datetime(val.year, val.month, val.day)
    else:
        s = str(val).strip()
        if not s:
            print(f"Date string is empty or None: {val}")
            return None

        # Erst dd.mm.yyyy[ HH:MM], dann ISO/Varianten
        try:
            if " " in s:
                dt = datetime.strptime(s, "%d.%m.%Y %H:%M")
            else:
                dt = datetime.strptime(s, "%d.%m.%Y")
        except Exception:
            dt = None
            for fmt in ("%Y-%m-%d", "%Y-%m-%d %H:%M", "%Y/%m/%d", "%d-%m-%Y", "%Y.%m.%d"):
                try:
                    dt = datetime.strptime(s, fmt)
                    break
                except ValueError:
                    continue
            if dt is None:
                print(f"Failed to format date '{val}': unsupported format")
                return None

    if output_format == "yyyy-mm":
        return dt.strftime("%Y-%m")
    if output_format == "yyyy-mm-dd":
        return dt.strftime("%Y-%m-%d")

    print(f"Unsupported output format: {output_format}")
    return None
from datetime import datetime, date

def parse_date(val):
    # None / leere Strings
    if val is None:
        return None
    if isinstance(val, str):
        s = val.strip()
        if not s:
            return None
    else:
        s = val  # kann date/datetime/int/float sein

    # Bereits datetime/date?
    if isinstance(s, datetime):
        return s.date()
    if isinstance(s, date):
        return s

    # Unix-Timestamp (int/float)?
    if isinstance(s, (int, float)):
        try:
            return datetime.fromtimestamp(s).date()
        except Exception:
            pass

    # String-Parsing
    s = str(s).strip()
    # ISO zuerst
    try:
        return date.fromisoformat(s)
    except Exception:
        pass

    # alternative Formate
    for fmt in ("%Y-%m-%d", "%d.%m.%Y", "%Y/%m/%d", "%d-%m-%Y", "%Y.%m.%d"):
        try:
            return datetime.strptime(s, fmt).date()
        except ValueError:
            continue

    # letzte Rettung: nichts parsebar
    # logger.warning(f"[parse_date] Could not parse {s!r}")
    return None
# ----------------------

