"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

LOG_PATH = None  # Wird beim Log-Setup gesetzt
_final_log_path = None
_last_message_was_inline = False  # Verfolgt, ob vorherige Ausgabe inline war


# --- Unicode path normalization helpers for macOS (APFS) ---
def _normalize_path(path: str) -> str:
    """Normalize Unicode for macOS (APFS often stores as NFD)."""
    try:
        import platform  # local import to avoid top-level duplication
        if platform.system() == "Darwin":
            return unicodedata.normalize("NFC", path)
    except Exception:
        pass
    return path


def safe_unlink(path: str) -> bool:
    """Remove a file or (even broken) symlink without raising outside.
    Returns True if something got removed.
    """
    path = _normalize_path(path)
    try:
        # lexists() is True for broken symlinks as well
        if os.path.lexists(path):
            try:
                os.unlink(path)
                return True
            except IsADirectoryError:
                shutil.rmtree(path)
                return True
        return False
    except FileNotFoundError:
        return False
    except PermissionError:
        # bubble up; caller should know they cannot write here
        raise
    except OSError:
        # last resort
        if os.path.exists(path):
            os.remove(path)
            return True
        return False


def message(text: str, target: str = "both", level: str = "info", inline: bool = False):
    global _last_message_was_inline

    prefix = {
        "info": "➕",
        "warn": "⚠️",
        "error": "❌"
    }.get(level, "➕")

    full_message = f"{prefix} {text}"

    # Wenn letzte Ausgabe inline war, füge einen echten Zeilenumbruch ein
    # if not inline and _last_message_was_inline:
    #     print()
    #     _last_message_was_inline = False

    if inline:
        print(full_message, end='\r', flush=True)
        _last_message_was_inline = True
        return

    if target in ("console", "both"):
        print(full_message)

    if target in ("log", "both") and LOG_PATH:
        try:
            # Kontextinfo für Log-Nachricht
            frame = inspect.currentframe().f_back
            filename = os.path.basename(frame.f_code.co_filename)
            line_number = frame.f_lineno
            function_name = frame.f_code.co_name
            context = f"{filename}:{line_number} [{function_name}]"
            with open(LOG_PATH, "a", encoding="utf-8") as f:
                f.write(f"{datetime.now()} - {context} {full_message}\n")
        except Exception as e:
            print(f"⚠️ Fehler beim Schreiben ins Log: {e}")

def set_log_path(path: str):
    global LOG_PATH
    LOG_PATH = path
    message(f"Log-Dateipfad gesetzt: {path}", target="console", level="info")

def mask_secret(secret: str, show: int = 4) -> str:
    """Maskiert einen String, zeigt nur die ersten und letzten Zeichen."""
    if not secret or len(secret) <= show * 2:
        return "*" * len(secret)
    return f"{secret[:show]}{'*' * (len(secret) - 2 * show)}{secret[-show:]}"

def initialize_log(log_dir, script_name, max_files):
    # get_log_filename() lebt in configutil.py. Verzoegerter Import hier
    # statt "from .configutil import ..." auf Modulebene, um einen echten
    # Zirkularimport zu vermeiden (configutil importiert seinerseits
    # message aus logutils).
    from .configutil import get_log_filename
    final_log_path = get_log_filename(script_name, log_dir, "log")
    progress_log_path = get_log_filename(script_name, log_dir, "progress")
    if os.path.exists(final_log_path):
        with open(progress_log_path, "w") as new_log, open(final_log_path, "r") as old_log:
            shutil.copyfileobj(old_log, new_log)
        os.remove(final_log_path)
    else:
        open(progress_log_path, "w").close()
    cleanup_old_files(log_dir, "" + script_name, max_files)
    return progress_log_path, final_log_path

def finalize_log():
    global LOG_PATH, _final_log_path
    if LOG_PATH and _final_log_path and os.path.exists(LOG_PATH):
        os.rename(LOG_PATH, _final_log_path)
        message("Log-Datei finalisiert.", target="console")

def prepare_logging(log_dir, script_name, max_files):
    global _final_log_path
    progress_log_path, final_log_path = initialize_log(log_dir, script_name, max_files)
    cleanup_old_files(log_dir,filename_prefix="" + script_name ,pattern="log",max_count_str=max_files)
    _final_log_path = final_log_path
    set_log_path(progress_log_path)
    atexit.register(finalize_log)

# Beispielverwendung nach Initialisierung:
# set_log_path("pfad/zur/logdatei.log")
# message("Export gestartet", target="both")
# message("Dokument konnte nicht geladen werden", level="warn")
# message("Verarbeite Dokument 17", inline=True)


# --- Version helpers ---

def print_separator(char='#', width_ratio=2/3):
    try:
        columns = shutil.get_terminal_size().columns
    except Exception:
        columns = 80  # fallback
    print()  # Zeilenumbruch vor dem Strich
    line_width = int(columns * width_ratio)
    print(char * line_width)

def cleanup_old_files(dir_path, filename_prefix, max_count_str, pattern="log"):
    """
    Löscht alte Dateien mit bestimmtem Prefix und Endung, wenn das Limit überschritten ist.

    :param dir_path: Verzeichnis, in dem gesucht wird
    :param filename_prefix: Anfang des Dateinamens, z. B. 'steuer'
    :param max_count_str: Maximale Anzahl an Dateien als String
    :param pattern: Dateityp bzw. Dateiendung, z. B. 'log' oder 'xlsx'
    """
    max_count = int(max_count_str)
    glob_pattern = os.path.join(dir_path, f"{filename_prefix}*.{pattern}")
    files = sorted(glob.glob(glob_pattern), key=os.path.getmtime)

   # print(f"\n[Cleanup] Suche: {glob_pattern} – gefunden: {len(files)} Dateien")

    if len(files) <= max_count:
   #     print(f"[Cleanup] Nichts zu tun: {len(files)} ≤ {max_count}")
        return

    while len(files) > max_count:
        old_file = files.pop(0)
        try:
            os.remove(old_file)
            print(f"[Cleanup] Datei gelöscht: {old_file}")
        except OSError as e:
            print(f"[Cleanup] Fehler beim Löschen von {old_file}: {e}")

# ----------------------
