"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message, mask_secret, prepare_logging, finalize_log
from .retry import retry_async
from .versioning import print_program_header
from .configutil import get_script_name, load_config_from_script, load_config, should_export
from .paperless_meta import fetch_paperless_meta
from .cache import build_all_cache, cleanup_all_dir
from .export_runner import exportThem
from .sp_tree import build_sp_structure, build_sp_excels

def is_remote_newer(remote_modified_str, local_path):
    # Vergleiche Timestamps
    remote_time = datetime.datetime.fromisoformat(remote_modified_str)
    local_time = datetime.datetime.fromtimestamp(os.path.getmtime(local_path))
    return remote_time > local_time


async def main():
    print_program_header()

    script_name = get_script_name()
    config = load_config_from_script()

    # 🔍 Pflichtfelder prüfen
    required = {
        "API": ["url", "token"],
        "Export": ["directory"],
        "Log": ["log_file", "max_files"]
    }

    missing = []
    for section, keys in required.items():
        if not config.has_section(section):
            missing.append(f"[{section}] fehlt")
            continue
        for key in keys:
            if not config.has_option(section, key) or not config.get(section, key).strip():
                missing.append(f"{section}.{key} fehlt oder ist leer")

    if missing:
        print("\n❌ Fehler in der Konfigurationsdatei:")
        for m in missing:
            print(f"   - {m}")
        print("\n💡 Bitte prüfe deine .ini-Datei und ergänze die fehlenden Angaben.")
        sys.exit(1)

    # ✅ Nur wenn alles ok ist: Konfigurationswerte lesen
    export_dir = config.get("Export", "directory")
    api_url = config.get("API", "url")
    api_token = config.get("API", "token")
    log_dir = config.get("Log", "log_file")
    max_files = config.get("Log", "max_files")

    # Log-Dateien initialisieren
    prepare_logging(log_dir, script_name, max_files)

    # Beispielverwendung nach Initialisierung:
    # set_log_path("pfad/zur/logdatei.log")
    # message("Export gestartet", target="both")
    # message("Dokument konnte nicht geladen werden", level="warn")
    # message("Verarbeite Dokument 17", inline=True)

# Setze das Arbeitsverzeichnis auf das Verzeichnis, in dem das Skript gespeichert ist
    script_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
    os.chdir(script_dir)

# Setze Locale früh im Programm (fallback auf Standard-Locale)
    try:
        locale.setlocale(locale.LC_ALL, 'de_DE.UTF-8')
    except locale.Error:
        try:
            locale.setlocale(locale.LC_ALL, '')
        except:
            print("⚠️ Locale konnte nicht gesetzt werden – Formatierung ggf. fehlerhaft.")

    message(f"Log in to {api_url} with {mask_secret(api_token)} ..", target="both")
    paperless = Paperless(api_url, api_token)
    await retry_async(lambda: paperless.initialize(), desc="Paperless-Login")
    
    message("Logged in", target="both")
    message(f"Export to {export_dir}", target="both")

    # do something
    meta = await fetch_paperless_meta(paperless)
    # Zugriff auf ein Element
    #print(meta["correspondents"][3].name)
    #print(meta["tags"][1].name)
    #print(meta["storage_paths"][2].name)

    await build_all_cache(paperless, export_dir)
    await cleanup_all_dir(paperless, all_dir=os.path.join(export_dir, ".all"))

    # --- SP-Struktur (Index + JSON + Pruning) ---
    # Läuft VOR den normalen Query-Exports, denn die brauchen die
    # SP-JSONs schon als Quelle zum Verlinken.
    sp_root = None
    sp_index = None
    try:
        sp_result = await build_sp_structure(paperless=paperless, meta=meta, export_dir=export_dir, api_url=api_url)
        sp_root = sp_result["sp_root"]
        sp_index = sp_result["index"]
        sp_folder_docs = sp_result["folder_docs"]
        sp_folder_currency = sp_result["folder_currency"]
    except Exception as e:
        message(f"❌ SP-Struktur fehlgeschlagen: {e}", target="both", level="warn")
        sp_folder_docs, sp_folder_currency = {}, {}

    excluded_dirs = {"@eaDir", ".all", "SP"}
    try:
        for root, dirs, files in os.walk(export_dir):
          query_value = os.path.basename(root)
          dirs[:] = [d for d in dirs if d not in excluded_dirs]
          if root == export_dir:
            continue

          config_mtime = 0  # oder datetime.min.timestamp()
          config = configparser.ConfigParser()
          if 'config.ini' in files:
              config_path = os.path.join(root, 'config.ini')
              #   config.read(config_path)
              config = load_config(config_path=config_path) or config
              config_mtime = os.path.getmtime(config_path)

          custom_field_query = None

          has_query = 'DATA' in config and 'query' in config['DATA']
          has_cf_query = 'DATA' in config and 'custom_field_query' in config['DATA']

          if has_query:
              query_value = config['DATA']['query']
          elif has_cf_query:
              # If only custom_field_query is given, don't use folder name as query.
              query_value = ''

          if has_cf_query:
              custom_field_query = config['DATA']['custom_field_query']

          if 'EXPORT' in config and 'frequency' in config['EXPORT']:
              frequency = config['EXPORT']['frequency']
          else:
              frequency = 'daily'

          should_run, reason = should_export(root, frequency, config_mtime)
          decision = "Export" if should_run else "Skip"
          symbol = "+" if should_run else "="
          display_dir = os.path.basename(root) or root
          print(f"{symbol} {display_dir} ({reason})")
          if should_run:
              await exportThem(paperless=paperless, dir=root, query=query_value, custom_field_query=custom_field_query, max_files=max_files,frequency=frequency, api_url=api_url, base_export_dir=export_dir, sp_root=sp_root, sp_index=sp_index)
          # Keine Separator-Ausgabe mehr – sauberere Konsole

        # --- SP-Excel (current+sub-Mappen) ---
        # Läuft NACH den normalen Query-Exports (wie besprochen), nutzt aber
        # die bereits in Phase A gesammelten Zeilen – kein zweiter Archiv-Scan.
        try:
            await build_sp_excels(
                export_dir=export_dir, meta=meta, url=api_url,
                folder_docs=sp_folder_docs, folder_currency=sp_folder_currency,
                script_name=get_script_name(),
            )
        except Exception as e:
            message(f"❌ SP-Excel fehlgeschlagen: {e}", target="both", level="warn")

    except Exception as e:
        message(f"Error: {str(e)}", target="both")
        raise
    finally:
        if paperless:
            await paperless.close()
        #finalize_log(progress_log_path, final_log_path)

