"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message
from .retry import retry_async

async def get_dict_from_paperless(endpoint):
    """
    Generische Funktion, um ein Dictionary aus einem Paperless-Endpoint zu erstellen.
    Erwartet ein `endpoint`-Objekt, das eine `all()`-Methode und einen Abruf per ID unterstützt.
    """
    items = await retry_async(fn=lambda: endpoint.all())
    #items = await endpoint.all()
    item_dict = {}

    for itemKey in items:
        item = await endpoint(itemKey)
        item_dict[item.id] = item  # Speichert das gesamte Objekt mit der ID als Schlüssel

    return item_dict  # Gibt ein Dictionary {ID: Objekt} zurück
# Modulweiter Cache (z. B. ganz oben im Script)
_paperless_meta_cache = None

async def fetch_paperless_meta(paperless, force_reload=False):
    global _paperless_meta_cache

    if _paperless_meta_cache is not None and not force_reload:
        return _paperless_meta_cache

    def log_and_print(name):
        message(text=f"getting {name}...",inline=True)

    meta = {}

    for name, endpoint in {
        "storage_paths": paperless.storage_paths,
        "correspondents": paperless.correspondents,
        "document_types": paperless.document_types,
        "tags": paperless.tags,
        "users": paperless.users,
        "custom_fields": paperless.custom_fields
    }.items():
        message(f"{name}",inline=True)
        try:
            meta[name] = await get_dict_from_paperless(endpoint)
            message(f"{name.capitalize()}: {len(meta[name])}")
        except Exception as e:
            message( f"Fehler beim Abrufen von {name}: {e}")
            meta[name] = {}  # Leere Liste als Fallback, damit getmeta nicht crasht

    _paperless_meta_cache = meta
    return meta

# ----------------------
def getmeta(key, doc, meta):
    """
    Liefert einen aufgelösten Namen (oder 'Unbekannt') für Felder wie:
      - 'correspondent'  -> meta['correspondents'][id].name
      - 'document_type'  -> meta['document_types'][id].name
      - 'storage_path'   -> meta['storage_paths'][id].name
      - 'tags'           -> Liste von IDs -> kommagetrennte Namen
    Arbeitet robust mit Dict-Metadaten und None/fehlenden IDs.
    """
    try:
        value = getattr(doc, key, None)

        # Tags: Liste von IDs -> kommagetrennte Namen
        if key == "tags":
            if not isinstance(value, list):
                return "Unbekannt"
            tags_map = meta.get("tags") or {}
            names = []
            for tid in value:
                obj = tags_map.get(tid)
                name = getattr(obj, "name", None) if obj else None
                if name:
                    names.append(name)
            return ", ".join(names) if names else "Unbekannt"

        # Einzelfelder: ID -> Objekt -> .name
        space = f"{key}s"  # correspondent -> correspondents, document_type -> document_types, storage_path -> storage_paths
        space_map = meta.get(space) or {}
        if value is None:
            return "Unbekannt"
        obj = space_map.get(value)
        if not obj:
            return "Unbekannt"
        return getattr(obj, "name", None) or getattr(obj, "username", "Unbekannt")
    except Exception as e:
        print(f"Fehler beim Auflösen von '{key}': {e}")
        return "Unbekannt"

