"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message

def _default_retry_exceptions():
    import aiohttp, asyncio
    excs = [aiohttp.ClientError, asyncio.TimeoutError, ConnectionResetError, BrokenPipeError]
    # Aiohttp: ServerDisconnectedError ist ein eigener Typ -> explizit mit rein
    try:
        from aiohttp.client_exceptions import ServerDisconnectedError
        excs.append(ServerDisconnectedError)
    except Exception:
        pass
    # pypaperless-Wrapper
    try:
        from pypaperless.exceptions import PaperlessConnectionError
        excs.append(PaperlessConnectionError)
    except Exception:
        pass
    return tuple(excs)

async def retry_async(fn, retries=5, delay=2, backoff=2.0, jitter=0.3,
                      exceptions=None, desc=None):
    """
    Führt fn() mit Exponential Backoff + leichtem Jitter aus.
    - exceptions: Tuple der Exceptions, die zu Retries führen (Default: Netzwerk + PaperlessConnectionError)
    """
    import random, shutil as _shutil, asyncio as _asyncio
    if exceptions is None:
        exceptions = _default_retry_exceptions()

    current_delay = float(delay)
    for attempt in range(1, retries + 1):
        try:
            return await fn()
        except exceptions as e:
            if attempt == retries:
                raise
            label = f' bei "{desc}"' if desc else ''
            term_width = _shutil.get_terminal_size((80, 20)).columns
            print(f"\r[retry_async] Fehler{label}: {e} – Versuch {attempt}/{retries}, nächster in {current_delay:.1f}s...".ljust(term_width), end='', flush=True)
            # kleiner Jitter, damit viele gleichzeitige Requests nicht synchron wieder zuschlagen
            wait = current_delay * (1.0 + random.uniform(-jitter, jitter))
            await _asyncio.sleep(max(0.1, wait))
            current_delay *= backoff

# ----------------------
