"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message
from . import paperless_meta
from .paperless_meta import getmeta
from .formatting import parse_date, format_date
from .document_row import process_custom_fields
from .file_linking import get_document_json, get_document_metadata

async def build_document_row(paperless, doc, meta, api_url):
    """
    Baut die Excel-Zeile (OrderedDict) für ein einzelnes Dokument, inkl.
    Custom Fields, Storage-Path-Infos und /metadata/-Feldern.

    Wird sowohl von exportThem() (Query-Export in die bestehenden Ordner)
    als auch von build_sp_tree() (Storage-Path-Schattenstruktur) benutzt,
    damit beide exakt das gleiche Zeilenformat liefern.

    Rückgabe: (row, doc_currency_columns, media_filename)
    media_filename wird zusätzlich zurückgegeben, weil build_sp_tree() ihn
    braucht, um den aufgelösten Zielordner (Storage Path) zu bestimmen.
    """
    api_base = api_url.rstrip("/")
    docData = doc._data
    page_count = docData['page_count']
    message(f"{doc.id} {doc.title} {page_count} pages", target="log")

    custom_fields, doc_currency_columns = process_custom_fields(meta=meta, doc=docData)
    thisTags = getmeta("tags", doc, meta=meta)

    # --- Normalize Storage Path into a constant prefix and a variable template tail ---
    sp_obj = meta["storage_paths"].get(doc.storage_path)
    sp_name = getattr(sp_obj, "name", "") if sp_obj else ""
    sp_template = ""
    if sp_obj:
        sp_template = getattr(sp_obj, "path", "") or getattr(getattr(sp_obj, "_data", {}), "get", lambda *_: "")("path") if hasattr(sp_obj, "_data") else ""

    _tpl = sp_template or ""
    if "{{" in _tpl:
        _pre, _tail = _tpl.split("{{", 1)
        sp_prefix = _pre.rstrip("/ ").strip()
        sp_tail = "{{" + _tail
    else:
        sp_prefix = _tpl.rstrip("/ ").strip()
        sp_tail = ""

    storage_group = sp_tail.strip() or sp_name or sp_prefix

    # Metadaten-JSON immer laden (Storage-Pfad & media_filename)
    meta_json = {}
    try:
        meta_json = get_document_metadata(paperless=paperless, doc=doc, api_base=api_base) or {}
    except Exception as e:
        message(f"Metadaten für Doc {doc.id} nicht geladen: {e}", target="log", level="warn")
        meta_json = {}

    # Medien-Dateiname – erst Basis, dann /metadata/, dann Dokument-JSON
    media_filename = docData.get("media_filename")
    if not media_filename:
        media_filename = meta_json.get("media_filename") or meta_json.get("original_filename")
    if not media_filename:
        try:
            doc_json = get_document_json(paperless=paperless, doc=doc, api_base=api_base)
            media_filename = doc_json.get("media_filename") or doc_json.get("original_file_name") or ""
        except Exception as e2:
            message(f"media_filename fehlend für Doc {doc.id}: {e2}", target="log", level="warn")
            media_filename = ""

    # Wichtige Metadaten-Felder aus /metadata/
    meta_size = meta_json.get("original_size") or meta_json.get("size") or ""
    meta_mime = meta_json.get("original_mime_type") or meta_json.get("mime_type") or meta_json.get("content_type") or ""
    meta_sha = meta_json.get("original_checksum") or meta_json.get("sha256") or meta_json.get("sha256sum") or ""
    meta_archive_size = meta_json.get("archive_size") or ""
    meta_archive_checksum = meta_json.get("archive_checksum") or ""
    meta_archive_filename = meta_json.get("archive_media_filename") or ""
    meta_original_filename = meta_json.get("original_filename") or ""
    meta_lang = meta_json.get("lang") or ""

    row = OrderedDict([
        ("ID", doc.id),
        ("LINK", doc.id),
        ("Korrespondent", getmeta("correspondent", doc, meta)),
        ("Titel", doc.title),
        ("Tags", thisTags),
        *custom_fields.items(),
        ("Seiten", doc._data['page_count']),
        ("Dokumenttyp", getmeta("document_type", doc, meta)),
        ("Speicherpfad", getmeta("storage_path", doc, meta)),
        ("ArchivDate", parse_date(doc.created)),
        ("ArchivedDateMonth", format_date(parse_date(doc.created), "yyyy-mm")),
        ("ArchivedDateFull", format_date(parse_date(doc.created), "yyyy-mm-dd")),
        ("ModifyDate", parse_date(doc.modified)),
        ("ModifyDateMonth", format_date(parse_date(doc.modified), "yyyy-mm")),
        ("ModifyDateFull", format_date(parse_date(doc.modified), "yyyy-mm-dd")),
        ("AddedDate", parse_date(doc.added)),
        ("AddDateMonth", format_date(parse_date(doc.added), "yyyy-mm")),
        ("AddDateFull", format_date(parse_date(doc.added), "yyyy-mm-dd")),
        ("OriginalName", doc.original_file_name),
        ("ArchivedName", doc.archived_file_name),
        ("Owner", getattr(meta["users"].get(doc.owner), "username", "Unbekannt") if doc.owner else "Unbekannt"),
        ("URL", f"{api_base}/documents/{doc.id}"),
        ("MetadataURL", f"{api_base}/api/documents/{doc.id}/metadata/"),
        ("MetadataOriginalFilename", meta_original_filename),
        ("MetadataMediaFilename", media_filename),
        ("MetadataArchiveFilename", meta_archive_filename),
        ("MetadataOriginalSize", meta_size),
        ("MetadataArchiveSize", meta_archive_size),
        ("MetadataOriginalMime", meta_mime),
        ("MetadataOriginalChecksum", meta_sha),
        ("MetadataArchiveChecksum", meta_archive_checksum),
        ("MetadataLang", meta_lang),
        ("MediaFilename", media_filename),
    ])

    return row, doc_currency_columns, media_filename


