"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .retry import retry_async

async def get_documents_with_retry(paperless, query):
    return await retry_async(
        lambda: collect_async_iter(paperless.documents.search(query)),
        desc=f"Dokumente für Query '{query}'"
    )

async def collect_async_iter(aiter):
    return [item async for item in aiter]

async def search_documents(paperless, query=None, custom_field_query=None):
    kwargs = {}
    if custom_field_query:
        kwargs["custom_field_query"] = custom_field_query

    # pypaperless v3: use reduce() context to apply filters, then iterate helper
    kwargs["query"] = query or ""
    async with paperless.documents.reduce(**kwargs):
        return [item async for item in paperless.documents]

