"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message
from .configutil import get_script_name, load_config
from .document_row import sanitize_filename
from .excel_export import export_sp_folder_excel
from .file_linking import get_document_json, get_document_metadata
from .row_builder import build_document_row
from .cache import safe_document_iterator

SP_INDEX_FILENAME = ".sp_index.json"


def _load_sp_index(export_dir):
    path = os.path.join(export_dir, SP_INDEX_FILENAME)
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        message(f"SP-Index konnte nicht gelesen werden, starte neu: {e}", target="both", level="warn")
        return {}


def _save_sp_index(export_dir, index):
    path = os.path.join(export_dir, SP_INDEX_FILENAME)
    tmp_path = path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(index, f, ensure_ascii=False, indent=2, sort_keys=True)
    os.replace(tmp_path, path)  # atomar


def _sp_json_target(sp_root, media_filename, doc_id):
    """
    Löst (rel_folder, json_filename, target_path) aus media_filename auf.
    Der Dateiname folgt dem echten Archivnamen (nicht dem ID-Präfix-Schema
    aus .all), mit der Doc-ID als Suffix für garantierte Eindeutigkeit.

    Gibt (None, None, None) zurück, wenn media_filename fehlt oder
    verdächtig aussieht (Path-Traversal).
    """
    if not media_filename:
        return None, None, None

    rel_folder = os.path.dirname(media_filename).lstrip("/")
    if rel_folder and (".." in rel_folder.split("/")):
        return None, None, None

    base_no_ext = os.path.splitext(os.path.basename(media_filename))[0]
    json_filename = f"{sanitize_filename(base_no_ext)}--{doc_id}.json"
    target_path = os.path.join(sp_root, rel_folder, json_filename) if rel_folder else os.path.join(sp_root, json_filename)
    return rel_folder, json_filename, target_path


def _prune_sp_tree(sp_root, active_rel_folders):
    """
    Entfernt aus dem SP-Baum alles, was zu keinem mehr aktiven Ordner gehört
    (weil sich der Storage Path eines Dokuments geändert hat), und räumt
    danach bottom-up leer gewordene Elternordner ab.

    Das ist exakt das Verhalten, das Paperless selbst im echten Archiv zeigt:
    wenn ein Dokument in einen anderen Ordner wandert, wird der alte Ordner
    gelöscht, sobald er leer ist – und wenn dadurch auch der Elternordner
    leer wird, verschwindet der ebenfalls.

    Gibt die Anzahl gelöschter Ordner zurück.
    """
    if not os.path.isdir(sp_root):
        return 0

    sp_root_norm = os.path.normpath(sp_root)
    active_abs = {os.path.normpath(os.path.join(sp_root, f)) for f in active_rel_folders if f}

    # Phase 1: Inhalte nicht mehr aktiver Ordner entfernen (unsere eigenen
    # generierten Dateien – Excel, JSON).
    for current_root, dirs, files in os.walk(sp_root):
        if os.path.normpath(current_root) == sp_root_norm:
            continue
        if os.path.normpath(current_root) not in active_abs:
            for fname in files:
                try:
                    os.remove(os.path.join(current_root, fname))
                except Exception:
                    pass

    # Phase 2: bottom-up leere Ordner entfernen (Kinder zuerst, dann Eltern –
    # dadurch kaskadiert das automatisch nach oben, ohne dass wir Eltern
    # explizit als "aktiv" markieren müssen).
    removed = 0
    for current_root, dirs, files in os.walk(sp_root, topdown=False):
        if os.path.normpath(current_root) == sp_root_norm:
            continue
        try:
            if not os.listdir(current_root):
                os.rmdir(current_root)
                removed += 1
        except Exception:
            pass

    return removed


async def build_sp_structure(paperless, meta, export_dir, api_url):
    """
    Phase A des SP-Baums – läuft früh, direkt bei/nach dem .all-Aufbau,
    BEVOR die normalen Query-Exports laufen (die brauchen die JSONs schon).

    - Iteriert EINMAL über das gesamte Archiv.
    - Schreibt/verschiebt JSON-Dateien nach SP/<aufgelöster Ordner>/, mit
      Bewegungserkennung über einen persistenten Index
      (export_dir/.sp_index.json): ändert sich der Storage Path eines
      Dokuments, wird das alte JSON im alten Ordner gelöscht und im neuen
      neu angelegt. Unveränderte Dokumente werden nicht neu von der API
      geholt (Modified-Zeitstempel + Dateiexistenz-Check).
    - Räumt verwaiste SP-Ordner weg (_prune_sp_tree).
    - Sammelt die Zeilen pro Ordner für die Excel-Mappen (Phase B,
      build_sp_excels() – läuft NACH den normalen Exports).

    Steuerung über [SP] mode = full/incremental in export_dir/config.ini
    (full: SP-Baum + Index komplett verwerfen und neu aufbauen).

    Gibt ein Dict mit sp_root/folder_docs/folder_currency/index/Statistiken
    zurück.
    """
    import time
    sp_root = os.path.join(export_dir, "SP")
    t_start = time.monotonic()

    root_config_path = os.path.join(export_dir, "config.ini")
    root_config = configparser.ConfigParser()
    if os.path.exists(root_config_path):
        root_config = load_config(config_path=root_config_path) or root_config

    sp_mode = "incremental"
    if "SP" in root_config and "mode" in root_config["SP"]:
        sp_mode = root_config["SP"]["mode"].strip().lower()

    message(f"SP-Struktur: Modus = {sp_mode} ({root_config_path})", target="both")

    index = {}
    if sp_mode == "full" and os.path.isdir(sp_root):
        message(f"SP-Struktur: vollständiger Neuaufbau – lösche {sp_root}", target="both")
        shutil.rmtree(sp_root)
        # Index ebenfalls verwerfen: alte Positionen sind nach dem Wipe irrelevant.
    elif sp_mode != "full":
        index = _load_sp_index(export_dir)

    os.makedirs(sp_root, exist_ok=True)
    api_base = api_url.rstrip("/")

    folder_docs = {}
    folder_currency = {}
    seen_ids = set()
    skipped = 0
    json_written = 0
    json_reused = 0
    json_deleted = 0

    async for doc in safe_document_iterator(paperless):
        try:
            row, doc_currency_columns, media_filename = await build_document_row(
                paperless=paperless, doc=doc, meta=meta, api_url=api_url
            )
        except Exception as e:
            message(f"SP-Struktur: Fehler bei Doc {getattr(doc, 'id', '?')}: {e}", target="log", level="warn")
            skipped += 1
            continue

        rel_folder, json_filename, target_path = _sp_json_target(sp_root, media_filename, doc.id)
        if rel_folder is None:
            if media_filename:
                message(f"SP-Struktur: verdächtiger Pfad übersprungen: {media_filename!r}", target="log", level="warn")
            skipped += 1
            continue

        doc_id_str = str(doc.id)
        seen_ids.add(doc_id_str)
        modified_str = str(getattr(doc, "modified", ""))
        old_entry = index.get(doc_id_str)

        moved = bool(old_entry) and (
            old_entry.get("rel_folder") != rel_folder or old_entry.get("json_filename") != json_filename
        )
        if moved:
            old_path = os.path.join(sp_root, old_entry["rel_folder"], old_entry["json_filename"]) \
                if old_entry.get("rel_folder") else os.path.join(sp_root, old_entry["json_filename"])
            if os.path.exists(old_path):
                try:
                    os.remove(old_path)
                    json_deleted += 1
                except Exception as e:
                    message(f"SP-Struktur: altes JSON konnte nicht gelöscht werden ({old_path}): {e}", target="log", level="warn")

        unchanged = (
            old_entry is not None
            and not moved
            and old_entry.get("modified") == modified_str
            and os.path.exists(target_path)
        )

        if not unchanged:
            try:
                os.makedirs(os.path.dirname(target_path) or sp_root, exist_ok=True)
                detailed_doc = get_document_json(paperless=paperless, doc=doc, api_base=api_base)
                with open(target_path, "w", encoding="utf-8") as jf:
                    json.dump(detailed_doc, jf, ensure_ascii=False, indent=4)
                json_written += 1
            except Exception as e:
                message(f"SP-Struktur: JSON-Export fehlgeschlagen für Doc {doc.id}: {e}", target="log", level="warn")
        else:
            json_reused += 1

        index[doc_id_str] = {"rel_folder": rel_folder, "json_filename": json_filename, "modified": modified_str}

        folder_docs.setdefault(rel_folder, []).append(row)
        folder_currency.setdefault(rel_folder, []).extend(doc_currency_columns)

    # Index-Einträge für gelöschte Dokumente entfernen (+ ihre JSON-Dateien)
    stale_ids = [doc_id for doc_id in list(index.keys()) if doc_id not in seen_ids]
    for doc_id in stale_ids:
        entry = index.pop(doc_id)
        stale_path = os.path.join(sp_root, entry["rel_folder"], entry["json_filename"]) \
            if entry.get("rel_folder") else os.path.join(sp_root, entry["json_filename"])
        if os.path.exists(stale_path):
            try:
                os.remove(stale_path)
                json_deleted += 1
            except Exception:
                pass

    _save_sp_index(export_dir, index)

    message(
        f"SP-Struktur: {len(folder_docs)} Ordner, {len(seen_ids)} Dokumente, {skipped} übersprungen, "
        f"JSON: {json_written} neu/aktualisiert, {json_reused} unverändert übernommen, {json_deleted} entfernt "
        f"(Scan: {time.monotonic() - t_start:.1f}s)",
        target="both",
    )

    pruned = _prune_sp_tree(sp_root, folder_docs.keys())
    if pruned:
        message(f"SP-Struktur: {pruned} verwaiste(n) Ordner entfernt (Storage Path geändert)", target="both")

    return {
        "sp_root": sp_root,
        "folder_docs": folder_docs,
        "folder_currency": folder_currency,
        "index": index,
        "skipped": skipped,
        "json_written": json_written,
        "json_reused": json_reused,
        "json_deleted": json_deleted,
    }


def find_sp_json_path(doc_id, sp_root, index):
    """Liefert den Pfad zur SP-JSON-Datei eines Dokuments laut Index, oder None."""
    if not index:
        return None
    entry = index.get(str(doc_id))
    if not entry:
        return None
    path = os.path.join(sp_root, entry["rel_folder"], entry["json_filename"]) \
        if entry.get("rel_folder") else os.path.join(sp_root, entry["json_filename"])
    return path if os.path.exists(path) else None


async def ensure_sp_json(paperless, doc, sp_root, api_url):
    """
    Fallback für exportThem(): falls ein Dokument (noch) keinen gültigen
    SP-Index-Eintrag hat (z.B. weil build_sp_structure() für dieses
    Dokument einen Fehler hatte, oder es neu hinzugekommen ist, nachdem
    die Struktur schon lief), wird die JSON-Datei hier on-demand direkt
    im SP-Baum erzeugt. Gibt den Zielpfad zurück oder None bei Fehler.
    """
    api_base = api_url.rstrip("/")
    try:
        meta_json = get_document_metadata(paperless=paperless, doc=doc, api_base=api_base) or {}
    except Exception:
        meta_json = {}

    media_filename = doc._data.get("media_filename") or meta_json.get("media_filename") or meta_json.get("original_filename")
    if not media_filename:
        try:
            doc_json = get_document_json(paperless=paperless, doc=doc, api_base=api_base)
            media_filename = doc_json.get("media_filename") or doc_json.get("original_file_name") or ""
        except Exception:
            media_filename = ""

    rel_folder, json_filename, target_path = _sp_json_target(sp_root, media_filename, doc.id)
    if rel_folder is None:
        return None

    try:
        os.makedirs(os.path.dirname(target_path) or sp_root, exist_ok=True)
        detailed_doc = get_document_json(paperless=paperless, doc=doc, api_base=api_base)
        with open(target_path, "w", encoding="utf-8") as jf:
            json.dump(detailed_doc, jf, ensure_ascii=False, indent=4)
        return target_path
    except Exception as e:
        message(f"ensure_sp_json: JSON-Fallback fehlgeschlagen für Doc {doc.id}: {e}", target="log", level="warn")
        return None


async def build_sp_excels(export_dir, meta, url, folder_docs, folder_currency, script_name):
    """
    Phase B des SP-Baums – läuft NACH den normalen Query-Exports.

    Erzeugt current+sub-Excelmappen NUR für Ordner, die direkt Dokumente
    enthalten (folder_docs.keys()) – reine Durchgangsordner (nur
    Unterordner, keine eigenen Dokumente direkt drin) bekommen keine Mappe.

    "sub" aggregiert rekursiv alle Dokumente dieses Ordners und aller
    Unterordner (Prefix-Match über die rel_folder-Schlüssel).
    """
    import time
    sp_root = os.path.join(export_dir, "SP")
    t_start = time.monotonic()
    written = 0

    all_folders = list(folder_docs.keys())

    for rel_folder, current_rows in folder_docs.items():
        if rel_folder == "":
            sub_folders = all_folders
        else:
            prefix = rel_folder + "/"
            sub_folders = [g for g in all_folders if g == rel_folder or g.startswith(prefix)]

        sub_rows = []
        sub_currency = []
        for g in sub_folders:
            sub_rows.extend(folder_docs[g])
            sub_currency.extend(folder_currency.get(g, []))

        target_dir = os.path.join(sp_root, rel_folder) if rel_folder else sp_root
        os.makedirs(target_dir, exist_ok=True)

        folder_label = rel_folder or "(root)"
        safe_name = sanitize_filename(os.path.basename(target_dir) or "SP")
        excel_file = os.path.join(target_dir, f"{safe_name}-{datetime.now().strftime('%Y%m%d')}.xlsx")

        export_sp_folder_excel(
            current_rows=current_rows, sub_rows=sub_rows,
            current_currency=folder_currency.get(rel_folder, []), sub_currency=sub_currency,
            file_path=excel_file, script_name=script_name, dir=target_dir,
            url=url, meta=meta, folder_label=folder_label,
        )
        written += 1

    message(
        f"SP-Excel: {written} Mappe(n) geschrieben (current+sub je Ordner mit eigenen Dokumenten) "
        f"(Dauer: {time.monotonic() - t_start:.1f}s)",
        target="both",
    )
    return written

