"""Auto-generated by split refactor (2026-08-15, SP-Baum mit JSON-Index +
current/sub-Excel). Common third-party/stdlib imports shared across all
paperless_export submodules."""
import os
import sys
import re
import json
import glob
import pwd
import shutil
import time
import atexit
import unicodedata
import locale
import inspect
import zipfile
import argparse
import pprint
import platform
import configparser
import subprocess
import urllib.request
from urllib.parse import quote
from time import sleep
from datetime import datetime, date, timedelta
from dateutil import parser
from collections import OrderedDict
from configparser import ConfigParser

import asyncio
import aiohttp
import requests
from tqdm import tqdm

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.formatting.rule import FormulaRule

from pypaperless import Paperless

from .logutils import message

def detect_git_version():
    try:
        version = subprocess.check_output(
            ["git", "describe", "--tags", "--always"],
            stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()
        return version
    except Exception:
        return None

def read_version_file(path=".version"):
    if os.path.exists(path):
        try:
            with open(path, "r") as f:
                return f.read().strip()
        except:
            pass
    return None

def fallback_version():
    dt = datetime.now().strftime("%Y%m%d-%H%M")
    return f"v0.0.0-{dt}-nogit"

def get_script_version(version_file=".version"):
    """
    Build a version string based on git tag + date + short commit hash.
    If git is not available, fall back to existing .version or generated fallback.
    """
    MAX_LEN = 120  # safeguard against path/file-name limits
    # Try reading git tag
    try:
        tag = subprocess.check_output(
            ["git", "describe", "--tags", "--abbrev=0"],
            stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()
    except Exception:
        tag = None

    # Try reading commit hash
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()
    except Exception:
        commit = None

    # Always include timestamp
    dt = datetime.now().strftime("%Y%m%d-%H%M")

    if tag and commit:
        version = f"{tag}-{dt}-{commit}"
        if len(version) > MAX_LEN:
            # shorten overly long tags to keep filenames/refnames safe
            tag_short = tag[:40]
            version = f"{tag_short}-{dt}-{commit}"
        try:
            with open(version_file, "w") as f:
                f.write(version)
        except:
            pass
        return version

    # If git is not available, try reading existing .version
    file_version = read_version_file(version_file)
    if file_version:
        if len(file_version) > MAX_LEN:
            return fallback_version()
        return file_version

    # Create fallback
    version = f"v0.0.0-{dt}-nogit"
    try:
        with open(version_file, "w") as f:
            f.write(version)
    except:
        pass
    return version

def get_github_repo_info():
    try:
        url = subprocess.check_output(
            ["git", "config", "--get", "remote.origin.url"],
            stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()

        # z. B. https://github.com/ufe-dev/paperless-ngx-2-excel.git
        # oder git@github.com:ufe-dev/paperless-ngx-2-excel.git

        match = re.search(r"github.com[:/](.+?)/(.+?)(\.git)?$", url)
        if match:
            user, repo = match.group(1), match.group(2)
            return user, repo
    except Exception:
        pass

    return None, None

def get_github_license_identifier(user, repo):
    url = f"https://api.github.com/repos/{user}/{repo}/license"
    try:
        with urllib.request.urlopen(url) as response:
            data = json.load(response)
            return data["license"]["spdx_id"]
    except Exception as e:
        print(f"⚠️ Lizenz konnte nicht geladen werden: {e}")
        return None

def print_program_header():
    script_name = os.path.basename(__file__)
    version = get_script_version()
    user, repo = get_github_repo_info()
    license_id = get_github_license_identifier(user, repo) if user and repo else "Unbekannt"
    github_url = f"https://github.com/{user}/{repo}" if user and repo else "(kein GitHub-Repo erkannt)"

    print(f"{script_name} {version} – © 2025 {license_id} – {github_url}", end="")



